#!/usr/bin/env bash
# test/run_tests.sh — loadout-pipeline test suite orchestrator.
#
# Sources the shared framework then each suite file in order. All suite files
# execute in this shell's scope so the PASS/FAIL counters and timing state
# remain consistent across the entire run without any IPC.
#
# Usage: bash test/run_tests.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURES_DIR="$ROOT_DIR/test/fixtures"
PIPELINE="${PIPELINE:-$ROOT_DIR/bin/loadout-pipeline.sh}"
EXTRACT_BASE="${EXTRACT_DIR:-/tmp/iso_pipeline}"

# Generate the default test jobs file at runtime from $ROOT_DIR so the
# test suite works in any clone location (WSL /mnt/c/..., Oracle Linux
# /tank/..., CI /home/runner/..., etc). A committed file with baked-in
# absolute paths would break the moment the repo moved off one machine.
# The file is written to /tmp with a per-run PID so parallel suites
# cannot collide.
TEST_JOBS="/tmp/iso_pipeline_test_jobs_$$.jobs"
cat > "$TEST_JOBS" <<EOF
# Auto-generated by test/run_tests.sh — do not edit manually.
# Regenerated on every test run so paths track \$ROOT_DIR at runtime.
~$FIXTURES_DIR/isos/game1.7z|ftp|/remote/path/game1~
~$FIXTURES_DIR/isos/game2.7z|hdl|/dev/hdd0~
~$FIXTURES_DIR/isos/game3.7z|sd|games/game3~
EOF
# Ensure this temporary jobs file is removed on every exit path so /tmp
# does not accumulate stale per-run files across repeated runs.
trap 'rm -f "$TEST_JOBS"' EXIT

# Default SD destination used by tests that do not set their own SD_MOUNT_POINT.
# Exported so all pipeline subprocesses pick it up automatically; tests that
# need isolation pass SD_MOUNT_POINT=<custom> inline to override it.
TEST_SD_DIR="/tmp/iso_pipeline_test_sd_default_$$"
mkdir -p "$TEST_SD_DIR"
export SD_MOUNT_POINT="$TEST_SD_DIR"

# Stub adapters (ftp, hdl, rclone, rsync) refuse to run by default so real
# pipeline invocations don't silently "succeed" without actually transferring
# anything. The test suite intentionally exercises those stubs (example.jobs
# has ftp/hdl entries, and 07_adapters.sh covers rclone/rsync), so opt in
# once globally here. A test that wants to verify the stub refusal can
# override with ALLOW_STUB_ADAPTERS=0 inline.
export ALLOW_STUB_ADAPTERS=1

PASS=0
FAIL=0

# ── shared framework (colours, timing, pass/fail/header, assertions) ──────────
source "$ROOT_DIR/test/helpers/framework.sh"

# ── test suites (sourced in order; all run in this shell's scope) ─────────────
source "$ROOT_DIR/test/suites/01_prerequisites.sh"
source "$ROOT_DIR/test/suites/02_core_pipeline.sh"
source "$ROOT_DIR/test/suites/03_precheck.sh"
source "$ROOT_DIR/test/suites/04_failure_handling.sh"
source "$ROOT_DIR/test/suites/05_space_ledger.sh"
source "$ROOT_DIR/test/suites/06_worker_registry.sh"
source "$ROOT_DIR/test/suites/07_adapters.sh"
source "$ROOT_DIR/test/suites/08_security.sh"
source "$ROOT_DIR/test/suites/09_real_archive.sh"
source "$ROOT_DIR/test/suites/10_regression.sh"
source "$ROOT_DIR/test/suites/11_wrapper_flatten.sh"
source "$ROOT_DIR/test/suites/12_resume_planner.sh"

# ── cleanup & summary ─────────────────────────────────────────────────────────
rm -rf "$TEST_SD_DIR"

_finish_test
_print_summary
[[ $FAIL -eq 0 ]]
